
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 28 18:41:52 CET 2023
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PROGRAM = 2;
  public static final int PROCEDURE = 10;
  public static final int SEMI = 8;
  public static final int LPAR = 6;
  public static final int STRING_LITERAL = 12;
  public static final int EOF = 0;
  public static final int ID = 11;
  public static final int error = 1;
  public static final int RPAR = 7;
  public static final int RETURN = 9;
  public static final int END = 5;
  public static final int BEGIN = 4;
  public static final int CLASS = 3;
}

