
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 28 12:40:56 CET 2023
//----------------------------------------------------

package expression_par;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int NUMBER = 5;
  public static final int TIMES = 3;
  public static final int EOF = 0;
  public static final int NEWLINE = 4;
}

