

     # [echo] clean                		- Cleans up the project
     # [echo] compile-example-eval 		- Compile Example Eval
     # [echo] run-example-eval     		- Run Example Eval
     # [echo] compile-example-parse  		- Compile Example Parse
     # [echo] run-example-parse      		- Run Example Parse


lex-eval:
	java -jar ../../../lib/JFlex.jar  expression-eval.lex

cup-eval:
	java -jar ../../../lib/java-cup-11a.jar expression-eval.cup

lex-parse:
	java -jar ../../../lib/JFlex.jar  expression-par.lex 

cup-parse:
	java -jar ../../../lib/java-cup-11a.jar expression-par.cup
