
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 05 09:37:52 CET 2020
//----------------------------------------------------

package expression_par;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int NUMBER = 5;
  public static final int TIMES = 3;
  public static final int EOF = 0;
  public static final int NEWLINE = 4;
}

