#+LINK: srcbytecode ../../../material/oblig2-patch/src/bytecode/%s
#+LINK: srcruntime ../../../material/oblig2-patch/src/runtime/%s

* Building a complete program

We have shown the basics of how a bytecode program (binary file) is built
using the bytecode library. In this section we will show some of the
details by covering each of the classes in the library. Details about all
the instructions will come in Section [[sec:rememberthis]].

The main parts for creating a new program are: create an object of the
class ~CodeFile~. Afterwards add the procedures, i.e., objects of class
~CodeProcedure~, structs, i.e., objects of class ~CodeStruct~, and so
on. Finally, when calling the ~getBytecode()~ procedure, the bytecode
library will generae the actual bytes from the object hat have been created
and from the ``properties'' given to those objects.

Note that there a /four/ steps to create a procedure (or a struct, or
global variable).

1. /add/ the definition to the ~CodeFile~ object via ~addProcedure~.
2. /create/ the ~CodeProcedure~ object via ~new CodeProcedure~.
3. /add/ ``properties'', such as the instructions, to the ~CodeProcedure~
   object.
4. /update/ the ~CodeProcedure~ object in the ~CodeFile~ via
   ~updateProcedure~


These four standard steps are illustrated in slightly more detail in the
following example.k

** A small example









