* Introduction

This report presents the local variant of /bytecode/, /bytecode
interpreter/, and /bytecode construction library/ written for the compiler
construction course INF5110 and the University of Oslo. The bytpecode
library and intepreter were developed to be used in the /code generation/
and /runtime/ part of the obligatory exercises in the course. The objective
of this exercise is to write a compiler for a simple example language.


Bytecodes in general similar to machine code, but instead of being run
directly on a machine, they are usually interpreted by a bytecode
interpreter. They may also be translated into machine code before being
run. A bytpecode nstruction library is a library to simplify the task of
generating bytecode for a bytecode interpreter. Bytecode is name exactly
that because each instruction is the size of a byte.

Our bytecode is quite similar to Java bytecode and our bytecode library is
based on the [[http://commons.apache.org/proper/commons-bcel/][Byte Code Engineering Library]].[fn:bcel] We choose to write a
simpler, stripped-down version that, for instance, does not support
classes, virtual procedures, and all the other things that Java's bytecode
has. We did that so that it would be simpler to work with, and there would
be less code. For instance, one does not need to create classes like, since
our language does not have them, just for ``some reasons
unexplained''. Still, we encorange students to look at BCEL, as it's a nice
tool and very well designed.




The bytecode library and the interpreter are, not surprisingly, written in
Java. All the code is written in source form and consists of the following
packages.

- ~bytecode.*~:    classes to create bytecode
- ~bytecode.instructions.*~  instruction classes, supporting the above
- ~bytecode.type.*~  type classes, supporting the above
- ~runtime.*~ : classes of the runtime system

** The interpreter

The interpreter is /stack based/ and it interprets about 40 different
instructions of our bytecode.  The interpreter ``automatically'' handles
allocation of struct types, method calls and access of variables in a
struct when instructed to, by the bytecode instructions. In the first
version it does /not/ have a garbage collector and allocates memory
sequentially as long as there is memory left.

The operators or instructions are so called stack operations. It means that
whe the intpreter executes an instruction, it pops off a number of operands
from the stack (0 or more), performs the task specified by the instruction,
and leaves a number of result values on the stack (typically just one such
value).



[fn:bcel] ~http://commons.apache.org/proper/commons-bcel/~, formerly as
part of the Jakarta project.
